In [1]:
import pandas as pd
import seaborn as sns
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.feature_selection import SelectKBest, chi2

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
from sklearn.metrics import accuracy_score

In [5]:
from sklearn.metrics import classification_report, confusion_matrix

In [6]:
from sklearn.svm import SVC

In [7]:
from sklearn.naive_bayes import GaussianNB

In [8]:
from sklearn.ensemble import BaggingClassifier

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
from sklearn.ensemble import RandomForestClassifier, VotingClassifier

In [11]:
from sklearn.model_selection import cross_val_score

In [13]:
mydata = pd.read_csv('heart_dataset_1.csv')

In [14]:
mydata

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
292   57    0   4       140   241    0        0      123      1      0.2   
293   45    1   1       110   264    0        0      132      0      1.2   
294   68    1   4       144   193    1        0      141      0      3.4   
295   57    1   4       130   131    0        0      115      1      1.2   
296   57    0   2       130   236    0        2      174      0      0.0   

     slope  ca  thal  target  
0        3   0     6       0  
1        2   3     3       1  
2        2   2     7       1  
3        3   0     3       0  
4        1   0     3       0  
..     ...  ..   ...     ...  
292      2   0     7       1  
293      2   0     7       1  
294      2   2     7       1  
295      2   1     7       1  
296      2   1     3       1  

[297 rows x 14 columns]

In [15]:
print(mydata.columns)

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')


In [16]:
print(mydata)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
292   57    0   4       140   241    0        0      123      1      0.2   
293   45    1   1       110   264    0        0      132      0      1.2   
294   68    1   4       144   193    1        0      141      0      3.4   
295   57    1   4       130   131    0        0      115      1      1.2   
296   57    0   2       130   236    0        2      174      0      0.0   

     slope  ca  thal  target  
0        3   0     6       0  
1        2   3     3     

In [17]:
x = mydata.drop('target', axis=1)

In [18]:
x

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
292   57    0   4       140   241    0        0      123      1      0.2   
293   45    1   1       110   264    0        0      132      0      1.2   
294   68    1   4       144   193    1        0      141      0      3.4   
295   57    1   4       130   131    0        0      115      1      1.2   
296   57    0   2       130   236    0        2      174      0      0.0   

     slope  ca  thal  
0        3   0     6  
1        2   3     3  
2        2   2     7  
3        3   0     3  
4        1   0     3  
..     ...  ..   ...  
292      2   0     7  
293      2   0     7  
294      2   2     7  
295      2   1     7  
296      2   1     3  

[297 rows x 13 columns]

In [19]:
y = mydata['target']

In [20]:
y


0      0
1      1
2      1
3      0
4      0
      ..
292    1
293    1
294    1
295    1
296    1
Name: target, Length: 297, dtype: int64

In [23]:
y.describe()

count    297.000000
mean       0.461279
std        0.499340
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000
Name: target, dtype: float64

In [24]:
print("values of columns of x are =", x.columns)

values of columns of x are = Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')


In [25]:
selection = SelectKBest(chi2, k=10).fit(x, y)

In [26]:
x_new=selection.transform(x)

In [27]:
scores=selection.scores_

In [28]:
print(scores)

[2.29176975e+01 7.44419531e+00 1.45915872e+01 1.67074632e+01
 2.08550836e+01 2.54731794e-03 8.13465196e+00 1.87053104e+02
 3.55080899e+01 6.85705327e+01 7.82883557e+00 8.27306134e+01
 6.52210927e+01]


In [29]:
scores

array([2.29176975e+01, 7.44419531e+00, 1.45915872e+01, 1.67074632e+01,
       2.08550836e+01, 2.54731794e-03, 8.13465196e+00, 1.87053104e+02,
       3.55080899e+01, 6.85705327e+01, 7.82883557e+00, 8.27306134e+01,
       6.52210927e+01])

In [30]:
print(x_new)

[[ 63.    1.  145.  ...   2.3   0.    6. ]
 [ 67.    4.  160.  ...   1.5   3.    3. ]
 [ 67.    4.  120.  ...   2.6   2.    7. ]
 ...
 [ 68.    4.  144.  ...   3.4   2.    7. ]
 [ 57.    4.  130.  ...   1.2   1.    7. ]
 [ 57.    2.  130.  ...   0.    1.    3. ]]


In [31]:
svc_model = SVC(kernel='linear', gamma='auto')

In [32]:
#svc_model = SVC()

In [33]:
bagg_model = BaggingClassifier(base_estimator=SVC, n_estimators=2, random_state=0)

In [34]:
gnb = GaussianNB()

In [35]:
gnb

GaussianNB()

In [36]:
x_train, x_test, y_train, y_test = train_test_split(x_new,y,test_size=0.3)

In [37]:
svc_model.fit(x_train,y_train)

SVC(gamma='auto', kernel='linear')

In [38]:
y_pred = svc_model.predict(x_test)

In [39]:
y_pred 

array([1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0], dtype=int64)

In [40]:
training_acc = svc_model.score(x_train,y_train)

In [41]:
validation_acc = svc_model.score(x_test,y_test)

In [42]:
accuracy_value = accuracy_score(y_pred,y_test)

In [43]:
print(training_acc)

0.8599033816425121


In [44]:
print(validation_acc)

0.8111111111111111


In [45]:
print("Accuracy of the SVM Model with holdout method is:", accuracy_value* 100)

Accuracy of the SVM Model with holdout method is: 81.11111111111111


In [46]:
print(confusion_matrix(y_test, y_pred))

[[41  8]
 [ 9 32]]


In [47]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.84      0.83        49
           1       0.80      0.78      0.79        41

    accuracy                           0.81        90
   macro avg       0.81      0.81      0.81        90
weighted avg       0.81      0.81      0.81        90



In [48]:
print(y_test)

221    1
18     0
177    0
108    1
283    0
      ..
113    1
271    0
213    0
235    0
286    0
Name: target, Length: 90, dtype: int64


In [49]:
print(y_pred)

[1 0 1 1 0 0 1 0 1 0 1 1 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1
 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 1 1 1 1 1
 1 1 0 0 0 1 0 1 1 1 1 1 0 0 0 0]


In [50]:
accuracy = cross_val_score(svc_model, x_new, y, scoring='accuracy', cv = 10)

In [51]:
accuracy 

array([0.9       , 0.9       , 0.83333333, 0.96666667, 0.83333333,
       0.76666667, 0.76666667, 0.86206897, 0.75862069, 0.86206897])

In [52]:
print("Accuracy of the SVM Model with Cross Validation is:",accuracy.mean() * 100)

Accuracy of the SVM Model with Cross Validation is: 84.49425287356324


In [53]:
# group / ensemble of models

In [54]:
estimator = []

In [55]:
estimator.append(('LR', LogisticRegression(solver ='liblinear')))

In [56]:
estimator.append(('SVC', SVC(kernel='linear')))

In [57]:
estimator.append(('GNB', GaussianNB()))

In [58]:
vot_hard = VotingClassifier(estimators = estimator, voting ='hard')

In [59]:
vot_hard.fit(x_train, y_train)

VotingClassifier(estimators=[('LR', LogisticRegression(solver='liblinear')),
                             ('SVC', SVC(kernel='linear')),
                             ('GNB', GaussianNB())])

In [60]:
y_pred = vot_hard.predict(x_test)

In [61]:
accuracy_value = accuracy_score(y_pred,y_test)

In [62]:
print("Accuracy of Majority Voting Algorithm Model with holdout is:", accuracy_value* 100)

Accuracy of Majority Voting Algorithm Model with holdout is: 84.44444444444444


In [63]:
accuracy = cross_val_score(vot_hard, x, y, scoring='accuracy', cv = 10)

In [64]:
print("Accuracy of Majority Voting Algorithm Model with Cross Validation is:",accuracy.mean() * 100)

Accuracy of Majority Voting Algorithm Model with Cross Validation is: 84.83908045977012
